/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_notorein_threedmodeling_CollisionDetector */

#ifndef _Included_com_notorein_threedmodeling_CollisionDetector
#define _Included_com_notorein_threedmodeling_CollisionDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_notorein_threedmodeling_CollisionDetector
 * Method:    detectCollision
 * Signature: (FFFFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_notorein_threedmodeling_CollisionDetector_detectCollision
        (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
