/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_notorein_threedmodeling_utils_Vector2D */

#ifndef _Included_com_notorein_threedmodeling_utils_Vector2D
#define _Included_com_notorein_threedmodeling_utils_Vector2D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_notorein_threedmodeling_utils_Vector2D
 * Method:    magnitude
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_notorein_threedmodeling_utils_Vector2D_magnitude
        (JNIEnv *, jobject);

/*
 * Class:     com_notorein_threedmodeling_utils_Vector2D
 * Method:    distanceTo
 * Signature: (Lcom/notorein/threedmodeling/utils/Vector2D;)D
 */
JNIEXPORT jdouble JNICALL Java_com_notorein_threedmodeling_utils_Vector2D_distanceTo
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_notorein_threedmodeling_utils_Vector2D
 * Method:    add
 * Signature: (DD)Lcom/notorein/threedmodeling/utils/Vector2D;
 */
JNIEXPORT jobject JNICALL Java_com_notorein_threedmodeling_utils_Vector2D_add
        (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_notorein_threedmodeling_utils_Vector2D
 * Method:    subtract
 * Signature: (DD)Lcom/notorein/threedmodeling/utils/Vector2D;
 */
JNIEXPORT jobject JNICALL Java_com_notorein_threedmodeling_utils_Vector2D_subtract
        (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_notorein_threedmodeling_utils_Vector2D
 * Method:    scale
 * Signature: (D)Lcom/notorein/threedmodeling/utils/Vector2D;
 */
JNIEXPORT jobject JNICALL Java_com_notorein_threedmodeling_utils_Vector2D_scale
        (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_notorein_threedmodeling_utils_Vector2D
 * Method:    dot
 * Signature: (Lcom/notorein/threedmodeling/utils/Vector2D;)D
 */
JNIEXPORT jdouble JNICALL Java_com_notorein_threedmodeling_utils_Vector2D_dot
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_notorein_threedmodeling_utils_Vector2D
 * Method:    normalize
 * Signature: ()Lcom/notorein/threedmodeling/utils/Vector2D;
 */
JNIEXPORT jobject JNICALL Java_com_notorein_threedmodeling_utils_Vector2D_normalize
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
