/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_notorein_threedmodeling_utils_ObjectModelTriangle */

#ifndef _Included_com_notorein_threedmodeling_utils_ObjectModelTriangle
#define _Included_com_notorein_threedmodeling_utils_ObjectModelTriangle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_notorein_threedmodeling_utils_ObjectModelTriangle
 * Method:    intersects
 * Signature: (Lcom/notorein/threedmodeling/utils/ObjectModelTriangle;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_notorein_threedmodeling_utils_ObjectModelTriangle_intersects
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_notorein_threedmodeling_utils_ObjectModelTriangle
 * Method:    getVertices
 * Signature: ()[Lcom/notorein/threedmodeling/utils/Vector3D;
 */
JNIEXPORT jobjectArray JNICALL Java_com_notorein_threedmodeling_utils_ObjectModelTriangle_getVertices
        (JNIEnv *, jobject);

/*
 * Class:     com_notorein_threedmodeling_utils_ObjectModelTriangle
 * Method:    getNormals
 * Signature: ()[Lcom/notorein/threedmodeling/utils/Vector3D;
 */
JNIEXPORT jobjectArray JNICALL Java_com_notorein_threedmodeling_utils_ObjectModelTriangle_getNormals
        (JNIEnv *, jobject);

/*
 * Class:     com_notorein_threedmodeling_utils_ObjectModelTriangle
 * Method:    getTexCoords
 * Signature: ()[Lcom/notorein/threedmodeling/utils/Vector2D;
 */
JNIEXPORT jobjectArray JNICALL Java_com_notorein_threedmodeling_utils_ObjectModelTriangle_getTexCoords
        (JNIEnv *, jobject);

/*
 * Class:     com_notorein_threedmodeling_utils_ObjectModelTriangle
 * Method:    getCentroid
 * Signature: ()Lcom/notorein/threedmodeling/utils/Vector3D;
 */
JNIEXPORT jobject JNICALL Java_com_notorein_threedmodeling_utils_ObjectModelTriangle_getCentroid
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
